# Generated by Django 4.2.11 on 2026-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
